Build e push de imagem OCI
imobanco/python-image pull request #8
Opened 2021-07-27 19:10 UTC by PedroRegisPOAR

## Resumo

Vou abrir e documentar após aberto

### Detalhes

2021-07-27 19:20 UTC, rodrigondec requested changes

2021-07-27 19:20 UTC, rodrigondec commented on .github/workflows/tests.yml
> +    - run: podman --version || echo podman not installed
Pode fazer um pipe de comandos no CI
```suggestion
    - run: |
        sudo apt-get purge -y podman containers-image containers-common
        sudo apt-get autoremove --purge
        sudo apt-get -y clean
        podman --version || echo podman not installed
```

2021-07-27 19:20 UTC, rodrigondec commented on Makefile
> +IMAGE_NAME=docker-python-image/python
Essas configs não estão consistentes com a do income-back. Lá temos o registry de fato do github e etc :thinking:

2021-07-27 19:51 UTC, PedroRegisPOAR commented on Makefile
> +IMAGE_NAME=docker-python-image/python
Modificado e testado.

2021-07-27 20:57 UTC, rodrigondec requested changes
Alguns vários detalhes bons para serem discutidos

2021-07-27 20:57 UTC, rodrigondec commented on Makefile
> +IMAGE=$(REGISTRY)/$(IMAGE_NAME):$(IMAGE_TAG)
Ainda está diferente!

Vamos padronizar como?

Nome a organização/repositório ficarão no **REGISTRY** ou no **IMAGE_NAME**?

```
GITHUB_REGISTRY=docker.pkg.github.com
IMAGE_NAME=imobanco/income-back/income-api
IMAGE_TAG=latest
INCOME_API_IMAGE=$(GITHUB_REGISTRY)/$(IMAGE_NAME):$(IMAGE_TAG)
```

2021-07-27 20:57 UTC, rodrigondec commented on .github/workflows/tests.yml
> +
Esse CI foi feito apenas para testar o PR fazendo o build das imagens!

O ideal é criar outro CI que rode no MERGE com DEV que faça o build e push!

2021-07-27 20:57 UTC, rodrigondec commented on .github/workflows/tests.yml
>      runs-on: ubuntu-18.04
Está faltando o build de produção

2021-07-27 20:57 UTC, rodrigondec commented on Makefile
> +REGISTRY=imobanco/docker-python-image
Além disso utilizaremos o Docker Registry (antigo) ou o Container Registry (novo)?

Entendi melhor lendo os links que vc colocou no PR.

Eu voto para usar o novo registry com a url https://ghcr.io

2021-07-27 20:57 UTC, rodrigondec commented on .github/workflows/tests.yml
> +        image: imobanco/docker-python-image/python
acho que serial bom colocar o resultado do nome da imagem do make build em um resultado do CI e utilizar o nome do resultado aqui ao invés de deixar hardcoded

2021-07-27 20:59 UTC, PedroRegisPOAR commented on .github/workflows/tests.yml
>      runs-on: ubuntu-18.04
> Está faltando o build de produção

Não estava claro na issue, tinha ficado na dúvida

2021-07-27 20:59 UTC, rodrigondec commented on .github/workflows/tests.yml
>      runs-on: ubuntu-18.04
Verdade, tem a issue separada né? Deixa quieto :rofl:

2021-07-27 21:00 UTC, PedroRegisPOAR commented on .github/workflows/tests.yml
> +        image: imobanco/docker-python-image/python
> acho que serial bom colocar o resultado do nome da imagem do make build em um resultado do CI e utilizar o nome do resultado aqui ao invés de deixar hardcoded

Não sei/lembro como faz isso, mas seria bom juntar num lugar só mesmo.

2021-07-27 21:01 UTC, PedroRegisPOAR commented on Makefile
> +REGISTRY=imobanco/docker-python-image
> Além disso utilizaremos o Docker Registry (antigo) ou o Container Registry (novo)?
> 
> Entendi melhor lendo os links que vc colocou no PR.
> 
> Eu voto para usar o novo registry com a url https://ghcr.io

Certo, mas o que precisa fazer para usar esse registry?

2021-07-27 21:01 UTC, rodrigondec commented on Makefile
> +REGISTRY=imobanco/docker-python-image
Só usar o link acredito. E talvez alterar o `--format docker` :thinking:

2021-07-27 21:01 UTC, PedroRegisPOAR commented on .github/workflows/tests.yml
> +
> Esse CI foi feito apenas para testar o PR fazendo o build das imagens!
> 
> O ideal é criar outro CI que rode no MERGE com DEV que faça o build e push!

Entendi. Notar que não existe branch dev, está se fazendo o merge para master direto.

2021-07-27 21:02 UTC, rodrigondec commented on .github/workflows/tests.yml
> +        image: imobanco/docker-python-image/python
Estou pensando, um `make imagem_name` que tenha um `echo $IMAGE_NAME` resolveria para pegar o nome da imagem.

Já para salvar no output dos steps, temos em algum canto :thinking:

2021-07-27 21:03 UTC, rodrigondec commented on .github/workflows/tests.yml
> +
É para a branch principal que quis dizer

2021-07-27 21:25 UTC, PedroRegisPOAR commented on Makefile
> +REGISTRY=imobanco/docker-python-image
Resolvido?

2021-07-27 21:25 UTC, rodrigondec commented on Makefile
> +REGISTRY=imobanco/docker-python-image
y

2021-07-27 22:17 UTC, rodrigondec commented on .github/workflows/tests.yml
> +        image: imobanco/docker-python-image/python
feito

2021-07-27 22:19 UTC, rodrigondec commented on .github/workflows/tests.yml
> +
Separar as actions de teste e push/deploy!

2021-07-28 19:02 UTC, PedroRegisPOAR commented on .github/workflows/tests.yml
> +
> Separar as actions de teste e push/deploy!

Acredito que feito.

Falta saber qual o evento que cada uma deve ser executada (no merge etc).

2021-07-28 19:27 UTC, rodrigondec requested changes
:thinking:

2021-07-28 19:27 UTC, rodrigondec commented on .github/workflows/push.yml
> +      - 'release/**'
```suggestion
on:
  push:
    branchs:
      - master
```

2021-07-28 19:27 UTC, rodrigondec commented on .github/workflows/push.yml
> +  push:
```suggestion
  push:
```

2021-07-28 19:27 UTC, rodrigondec commented on .github/workflows/push.yml
> +    name: Push
```suggestion
    name: Build & Push
```

2021-07-28 19:27 UTC, rodrigondec commented on Containerfile.prod
> +FROM python:3.8.3-slim-buster
está igual à de dev no momento?

2021-07-28 19:27 UTC, rodrigondec commented on Makefile
>  prod.build:
```suggestion
build.prod:
```

2021-07-28 19:27 UTC, rodrigondec commented on .github/workflows/push.yml
> +        make prod.build
```suggestion
        make build.prod
```

2021-07-28 19:27 UTC, rodrigondec commented on .github/workflows/tests.yml
> +        make prod.build
```suggestion
        make build.prod
```

2021-07-28 19:29 UTC, PedroRegisPOAR commented on Makefile
>  prod.build:
Antes estava prod.build (acho que foi tu que fez kkkk)

2021-07-28 19:32 UTC, PedroRegisPOAR commented on Containerfile.prod
> +FROM python:3.8.3-slim-buster
Quase, apenas `ENV PIP_DISABLE_PIP_VERSION_CHECK 1` que está diferente, em prod está desabilitando a warn do pip que aparece toda vez que existe versão mais recente.

2021-07-28 19:32 UTC, rodrigondec approved these changes

2021-07-28 19:32 UTC, rodrigondec commented on Containerfile.prod
> +FROM python:3.8.3-slim-buster
Eu diria então pra deixar a mesma e termos uma imagem só :thinking:

2021-07-28 19:34 UTC, PedroRegisPOAR commented on Containerfile.prod
> +FROM python:3.8.3-slim-buster
> Eu diria então pra deixar a mesma e termos uma imagem só thinking

Não sei, não está muito claro o que vai ocorrer mais a frente, pode ser que ainda exista alguma diferença que não estamos vendo ainda.

2021-07-28 19:34 UTC, rodrigondec commented on Containerfile.prod
> +FROM python:3.8.3-slim-buster
Justo

2021-07-28 19:37 UTC, merged